zenml-io/zenml-dashboard

src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedSidebar/Menu/index.tsx

check for Stackcomponents

---

src/api/mockApiData.ts
src/api/stacks/getMyStacksApi.ts
src/redux/actions/stacks/getMyStacksAction.ts
src/ui/layouts/pipelines/Pipelines/List/index.tsx
src/ui/layouts/stacks/Stacks/useService.ts

resolve (stacks data rendering in pipeline)

---

global.d.ts
src/ui/layouts/pipelines/RunsTable/index.tsx
src/ui/layouts/runs/RunDetail/index.tsx
src/ui/layouts/runs/RunDetail/useService.ts

Fixed run details undefined issue.

fixed run detail issue

---

src/ui/components/Filters/index.tsx
src/ui/layouts/pipelines/Pipelines/List/index.tsx
src/ui/layouts/pipelines/Pipelines/List/useService.ts
src/ui/layouts/pipelines/Pipelines/index.tsx
src/ui/layouts/stackComponents/Stacks/List/index.tsx
src/ui/layouts/stackComponents/Stacks/List/useService.ts
src/ui/layouts/stackComponents/Stacks/index.tsx

Filters are applied to pipelines, stacks, and stack components.

filter for stack, stack component and pipeline

---

src/routes/routePaths.tsx
src/ui/layouts/pipelines/RunDetail/index.tsx
src/ui/layouts/runs/RunDetail/index.tsx
src/ui/layouts/session/Login/Form.tsx
src/ui/layouts/session/Login/useService.ts
src/ui/layouts/stackComponents/RunDetail/index.tsx
src/ui/layouts/stacks/RunDetail/index.tsx

Remove the details bar from the run details page and update endpoints.

remove detail bars from run details page and update end point

---

src/api/organizations/getInviteByCodeApi.ts

remove dead code

---

src/ui/layouts/pipelines/Pipelines/useService.ts
src/ui/layouts/pipelines/useService.ts
src/ui/layouts/stackComponents/Stacks/useService.ts
src/ui/layouts/stackComponents/useService.ts

fixed polling for pipeline and stackComponents

---

src/ui/layouts/pipelines/RunDetail/useService.ts
src/ui/layouts/runs/RunDetail/useService.ts
src/ui/layouts/stackComponents/RunDetail/useService.ts
src/ui/layouts/stacks/RunDetail/useService.ts

fixed graph rendering issue

---

src/routes/appRoutesConfig.tsx
src/routes/index.tsx
src/routes/utils/isRouteFound.ts
src/routes/utils/replaceRouteIfNeeded.ts
src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedHeader.tsx
src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedSidebar/Menu/index.tsx
src/ui/layouts/pipelines/BasePage.tsx
src/ui/layouts/pipelines/PipelineDetail/index.tsx
src/ui/layouts/pipelines/Pipelines/index.tsx
src/ui/layouts/session/Login/index.tsx
src/ui/layouts/session/Login/useService.ts
src/ui/layouts/stackComponents/BasePage.tsx
src/ui/layouts/stackComponents/Stacks/List/index.tsx
src/ui/layouts/stackComponents/Stacks/index.tsx
src/ui/layouts/stacks/BasePage.tsx
src/ui/layouts/stacks/Stacks/index.tsx

redirect via url

---

src/ui/layouts/common/Table/index.tsx

https://zenml.atlassian.net/browse/DAS-376

handled total width of table while resizing

---

src/ui/components/forms/index.tsx
src/ui/components/inputs/index.tsx
src/ui/layouts/connectors/ConnectorDetail/ConnectorComponents/getHeaderCols.tsx
src/ui/layouts/connectors/ConnectorDetail/ConnectorComponents/useService.ts
src/ui/layouts/connectors/ConnectorDetail/getHeaderCols.tsx
src/ui/layouts/connectors/Connectors/List/getHeaderCols.tsx
src/ui/layouts/connectors/RegisterConnector/CreateConnector/index.tsx
src/ui/layouts/connectors/RegisterConnector/SidePopup/index.tsx
src/ui/layouts/stackComponents/ConfigureComponent/CreateComponent/index.tsx
src/ui/layouts/stackComponents/ConfigureComponent/index.tsx
src/ui/layouts/stackComponents/ConfigureComponent/useService.ts
src/ui/layouts/stackComponents/ServicesSelectorComponent/Disabled.tsx
src/ui/layouts/stackComponents/ServicesSelectorComponent/index.tsx
src/ui/layouts/stackComponents/StackDetail/Configuration/index.module.scss
src/ui/layouts/stackComponents/StackDetail/Configuration/index.tsx
src/ui/layouts/stackComponents/StackDetail/Configuration/useService.ts
src/ui/layouts/stackComponents/StackDetail/index.tsx
src/ui/layouts/stackComponents/StackDetail/useService.ts
src/ui/layouts/stackComponents/UpdateComponent/UpdateConfig/index.tsx
src/ui/layouts/stackComponents/UpdateComponent/index.tsx
src/ui/layouts/stackComponents/UpdateComponent/useService.ts

We have resolved the bugs. Please review them.
https://zenml.atlassian.net/browse/DAS-384
https://zenml.atlassian.net/browse/DAS-388
https://zenml.atlassian.net/browse/DAS-391
https://zenml.atlassian.net/browse/DAS-383
https://zenml.atlassian.net/browse/DAS-387
https://zenml.atlassian.net/browse/DAS-389
https://zenml.atlassian.net/browse/DAS-394
https://zenml.atlassian.net/browse/DAS-393
https://zenml.atlassian.net/browse/DAS-399
https://zenml.atlassian.net/browse/DAS-392

Qa fixes connectors

---

.github/teams.yml

**Changed**:
- add `avishniakov` to `teams.yaml`

Adding avishniakov to the team

---

src/index.css
src/ui/components/lineage/index.module.scss
src/ui/components/lineage/index.tsx

https://github.com/zenml-io/zenml-dashboard/issues/356

fixed issue related zoom in controls

---

src/ui/layouts/settings/ConnectHub.tsx

https://zenml.atlassian.net/browse/DAS-419

changed the URL for hub docs

---

.env
src/ui/components/lineage/index.css
src/ui/components/lineage/index.module.scss
src/ui/components/lineage/sidebarTabsSwitchers/artifact.module.scss
src/ui/components/lineage/sidebarTabsSwitchers/artifactTabSwitcher.tsx
src/ui/components/lineage/sidebarTabsSwitchers/stepTabSwitcher.tsx
src/ui/layouts/NonEditableRunConfigNew/index.module.scss
src/ui/layouts/NonEditableRunConfigNew/index.tsx
src/ui/layouts/common/FormElement/index.tsx
src/ui/layouts/connectors/ConnectorTypes/SidePopup/index.module.scss
src/ui/layouts/runs/BasePage.tsx
src/ui/layouts/runs/RunDetail/Configuration/index.module.scss
src/ui/layouts/runs/RunDetail/Configuration/index.tsx
src/ui/layouts/settings/PersonalDetails.tsx

Updated the runs config side-tabs as per the new design

Runs config updated

---

src/ui/components/lineage/sidebarTabsSwitchers/artifactTabSwitcher.tsx

fixed artifact Id.
https://zenml.atlassian.net/browse/DAS-447

fixed artifact Id

---

src/api/types.ts
src/api/workspaces/getMyWorkspacesApi.ts
src/redux/reducers/runsReducer.ts
src/redux/reducers/workspacesReducer.ts
src/redux/selectors/workspaces.ts

https://zenml.atlassian.net/browse/DAS-455

added response types for workspace

---

src/ui/layouts/stackComponents/Component.tsx
src/ui/layouts/stackComponents/ConfigureComponent/CreateComponent/index.tsx
src/ui/layouts/stackComponents/ConfigureComponent/CreateComponent/useService.ts
src/ui/layouts/stackComponents/ConfigureComponent/useService.ts
src/ui/layouts/stackComponents/Header/CreatePipelineButton.tsx
src/ui/layouts/stackComponents/Header/DocumentationLink.tsx
src/ui/layouts/stackComponents/RegisterComponents/ListForAll/useService.ts
src/ui/layouts/stackComponents/RegisterComponents/useService.ts
src/ui/layouts/stackComponents/RunDetail/Configuration/index.tsx
src/ui/layouts/stackComponents/RunDetail/DAG/index.tsx
src/ui/layouts/stackComponents/RunDetail/DAG/useService.ts
src/ui/layouts/stackComponents/RunDetail/HeaderCols/index.tsx
src/ui/layouts/stackComponents/RunDetail/components.tsx
src/ui/layouts/stackComponents/RunDetail/useService.ts
src/ui/layouts/stackComponents/RunsTable/HeaderCols/index.tsx
src/ui/layouts/stackComponents/RunsTable/RunStatus/index.tsx
src/ui/layouts/stackComponents/RunsTable/index.tsx
src/ui/layouts/stackComponents/RunsTable/useService.ts
src/ui/layouts/stackComponents/ServicesSelectorComponent/index.tsx
src/ui/layouts/stackComponents/StackDetail/getHeaderCols.tsx
src/ui/layouts/stackComponents/StackDetail/useService.ts
src/ui/layouts/stackComponents/Stacks/AllRuns/index.tsx
src/ui/layouts/stackComponents/Stacks/List/RunsForStackTable/index.tsx
src/ui/layouts/stackComponents/Stacks/List/getHeaderCols.tsx
src/ui/layouts/stackComponents/UpdateComponent/getHeaderCols.tsx
src/ui/layouts/stackComponents/UpdateComponent/index.tsx
src/ui/layouts/stackComponents/UpdateComponent/useService.ts

removed unused code
and refactored repeated code

stack components refactor

---

src/ui/layouts/connectors/RegisterConnector/CreateConnector/index.tsx

https://zenml.atlassian.net/browse/DAS-432

remove empty values from payload

---

src/ui/layouts/NonEditableConfig/index.tsx
src/ui/layouts/common/StackBox/index.tsx

https://zenml.atlassian.net/browse/DAS-460

remove titlecase for component name

---

src/ui/layouts/connectors/ServicesSelectorComponent/index.tsx

https://zenml.atlassian.net/browse/DAS-461

fixed error tooltip

---

README.md

fix small typos on README.md

---

src/ui/components/dag/index.tsx
src/ui/components/dag/useService.ts
src/ui/components/lineage/index.tsx

https://zenml.atlassian.net/browse/DAS-469

remove polling and added refresh button

---

src/routes/routePaths.tsx
src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedSidebar/Menu/index.tsx

https://zenml.atlassian.net/browse/DAS-469

change url naming

---

src/layouts/AuthenticatedLayout/Sidebar.tsx

Updates to Sidebar

---

src/app/settings/LayoutSidebar.tsx
src/app/settings/notifications/NotificationsForm.tsx
src/app/settings/notifications/form-schema.ts
src/app/settings/notifications/page.tsx
src/router/Router.tsx
src/router/routes.tsx

Notification Settings

---

src/app/onboarding/ProductionSetup/index.tsx
src/app/onboarding/StarterSetup/Items.tsx
src/app/onboarding/StarterSetup/index.tsx
src/app/onboarding/page.tsx
src/components/onboarding/ChecklistItem.tsx
src/layouts/AuthenticatedLayout/OnboardingItem.tsx
src/lib/constants.ts
src/lib/onboarding.spec.ts
src/lib/onboarding.ts
src/lib/server.spec.ts
src/lib/server.ts
src/types/server.ts

Minor bugfixes

---

src/app/pipelines/columns.tsx
src/layouts/AuthenticatedLayout/index.tsx

Small Fixes

---

src/app/runs/[id]/Dag.tsx
src/components/dag-visualizer/Controls.tsx

feat: add refresh button to dag

---

src/app/pipelines/columns.tsx
src/app/runs/[id]/_Tabs/Overview/ComponentCollapsible.tsx
src/components/CollapsibleCard.tsx
src/components/MetadataCards.tsx
src/components/NestedCollapsible.tsx

- allow stack component settings to be nestable
- sort metadata alphabetically
- fix for pipelines without a run

Various fixes

---

src/components/steps/step-sheet/DetailsTab.tsx
src/data/api.ts
src/data/code-repositories/code-repositories-detail-query.ts
src/types/artifact-versions.ts
src/types/code-repository.ts

📝 ##fix/PRD-429-code-repo-fixes

feat: add connectors video (#598)

---

src/app/stacks/columns.tsx
src/components/stacks/Sheet/IntegrationsContext.tsx
src/components/stacks/Sheet/index.tsx

feat: display integrations

---

src/app/stacks/create/new-infrastructure/Providers/Azure.tsx
src/app/stacks/create/new-infrastructure/Providers/PermissionsCard.tsx
src/app/stacks/create/new-infrastructure/Providers/index.tsx
src/app/stacks/create/new-infrastructure/Steps/Deploy/ButtonStep.tsx
src/app/stacks/create/new-infrastructure/Steps/Deploy/ProvisioningStep.tsx
src/app/stacks/create/new-infrastructure/Steps/Provider.tsx
src/app/stacks/create/new-infrastructure/page.tsx
src/components/NumberBox.tsx
src/components/stacks/Sheet/index.tsx

Azure 1 Click Deployment

---

src/app/runs/[id]/_Tabs/Configuration/ParameterCollapsible.tsx
src/app/runs/[id]/_Tabs/Configuration/index.tsx
src/components/NestedCollapsible.tsx
src/data/api.ts
src/data/pipeline-deployments/index.ts
src/data/pipeline-deployments/pipeline-deployments-detail.ts
src/types/pipeline-deployments.ts

Update Pipeline Params

---

package.json
pnpm-lock.yaml
src/app/runs/[id]/_Tabs/Configuration/index.tsx
src/app/runs/[id]/page.tsx
src/components/artifacts/artifact-node-sheet/SheetContent.tsx
src/components/artifacts/artifact-node-sheet/VisualizationTab.tsx

Add Error Boundary to Visualization

---

src/app/components/StackComponentList.tsx
src/app/components/columns.tsx
src/app/components/page.tsx
src/app/components/service.ts
src/app/stacks/StackList.tsx
src/app/stacks/page.tsx
src/components/breadcrumbs/Breadcrumbs.tsx
src/components/breadcrumbs/SegmentsBreadcrumbs.tsx
src/components/stack-components/ComponentFallbackDialog.tsx
src/data/components/index.ts
src/layouts/AuthenticatedLayout/Sidebar.tsx
src/layouts/StackComponentsLayout/Header.tsx
src/layouts/StackComponentsLayout/Tabs.tsx
src/layouts/StackComponentsLayout/index.tsx
src/router/Router.tsx
src/router/routes.tsx

Add List for Stack Components

---

src/app/components/create/flavor-step.tsx
src/app/onboarding/Setup/Items.tsx
src/app/page.tsx
src/components/repositories/RepoBadge.tsx
src/components/stack-components/create-component/configuration-form.tsx
src/components/stack-components/create-component/flavor-select.tsx
src/components/stack-components/create-component/info-tile.tsx

- Remove VsCode Box from the overview page
- Add fallback Icon for flavors during component creation

Small Adjustments

---

src/components/logs/enhanced-log-viewer.tsx

Obviously the component names are Collapse and Expand which I didn't change, so perhaps those need changing as well?

Change tooltip title for text wrapping toggle
